server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://postgres:ELRtmspxfbYMFM9m3VwQ@containers-us-west-36.railway.app:5668/railway
    username: postgres
    password: ELRtmspxfbYMFM9m3VwQ

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
cache:
  update:
    in: 15
  expire:
    delay:
      in: 30

  scheduling:
    enabled: true